spring:
    datasource:
        password: postgres
        url: "jdbc:postgresql://localhost:5432/transport"
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
    mail:
        host: smtp.gmail.com
        password: pocmrjzfgqxpseoi
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: 015coders015@gmail.com