runtime: java
env: flex

profiles:
  staging:
    runtime: java
    env: flex
    env_variables:
      MY_VAR: staging
      SPRING_PROFILES_ACTIVE: cloud
  production:
    runtime: java
    env: flex
    env_variables:
      MY_VAR: production
      SPRING_PROFILES_ACTIVE: production